#!/bin/bash

### jcurl
sudo curl -L https://raw.githubusercontent.com/jeffreybaquiran/jeffreybaquiran.github.io/master/jcurl -o /usr/local/bin/jcurl
sudo chmod a+rx /usr/local/bin/jcurl

### youtube-dl
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

### ffmpeg
ffmpeg_url="http://www.ffmpegmac.net/resources/Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_08.02.2017.zip"
ffmpeg_filename=$(basename $ffmpeg_url)
sudo curl -O $ffmpeg_url
sudo unzip $ffmpeg_filename
sudo rm ffprobe
sudo rm ffserver
sudo mv ffmpeg /usr/local/bin/ffmpeg
sudo chmod a+rx /usr/local/bin/ffmpeg
sudo rm $ffmpeg_filename

### rclone
rclone_url="http://downloads.rclone.org/rclone-v1.35-osx-amd64.zip"
rclone_filename=$(basename $rclone_url)
rclone_folder=$(basename $rclone_url .zip)
sudo curl -O $rclone_url
sudo unzip $rclone_filename
sudo mv $rclone_folder /usr/local/bin/rclone.bin
sudo chmod a+rx /usr/local/bin/rclone.bin/rclone
sudo ln -s /usr/local/bin/rclone.bin/rclone /usr/local/bin/rclone
sudo rm $rclone_filename

exit 0
