#!/bin/bash

### jcurl created by Jef
### This intended for his own use.


option1=$1
list1="$2"
logfiledir1="/Users/Shared/.jef"
logfiledir2="/Users/Shared/.jef/jcurl"
logfile1="$logfiledir1/jcurl/jcurl_`date +%Y-%m-%d_%H-%M-%S`.log"
currentuser1=$(/usr/bin/last -1 -t console | awk '{print $1}')

if [ -z $1  ]; then
  echo "`date`"
  echo "Error: No option input. Type help for manual."
  exit 0
fi

if [ $1 = "help"  ]; then
  echo "To download single url"
  echo "Example: sudo jcurl -s [URL]"
  echo "To download multiple url"
  echo "Example: sudo jcurl -l [ListFile]"
  exit 0
fi

cd /Users/$currentuser1/Downloads
echo "Download folder is /Users/$currentuser1/Downloads"

if [ ! -d $logfiledir1 ]; then
  echo "`date`: Folder $logfiledir1 not found..."
  echo "`date`: Creating folder $logfiledir1"
  sudo mkdir $logfiledir1
  sudo ln -s $logfiledir1 /var/log/jef
fi

if [ ! -d $logfiledir2 ]; then
  echo "`date`: Folder $logfiledir2 not found..."
  echo "`date`: Creating folder $logfiledir2"
  sudo mkdir $logfiledir2
  sudo ln -s $logfiledir1 /var/log/jef/jcurl
fi

if [[ $option1 = "-l"  ]]; then
for i in $(cat "$list1")
	do
		echo "`date`: Downloading from $list1"	>> ${logfile1}
		echo " "
		echo "`date`: Downloading $i"	>> ${logfile1}
		curl --progress-bar -O -J -L $i >> ${logfile1} &
		echo " "
		echo "`date`: Finished downloading $i"	>> ${logfile1}
	done
fi

if [[ $option1 = "-s"  ]]; then
		echo "`date`: Downloading $2"	>> ${logfile1}
		echo " "
		curl --progress-bar -O -J -L $2 >> ${logfile1} &
		echo " "
		echo "`date`: Finished downloading $i"	>> ${logfile1}
fi

exit 0
