#!/bin/bash

### jef created by Jef
### This intended for his own use.

option1="$1"
option2="$2"

if [ $1 = "unmount"  ]; then
  echo "Unmounting $2"
  sudo diskutil unmountDisk force $2

elif [ $1 = "mountdmg"  ]; then
  echo "Mounting DMG $2"
  sudo hdiutil attach $2

elif [ $1 = "listmountdmg"  ]; then
    echo "Listing mounted DMG(s)"
    sudo diskutil list | grep "disk image"

fi

exit 0
