#!/bin/bash

### jef created by Jef
### This intended for his own use.

option1="$1"
option2="$2"

if [ $1 = "unmount"  ]; then
  echo "Unmounting $2"
  sudo diskutil unmountDisk force $2
  exit 0
fi

exit 0
