#!/bin/bash

option1="$1"
option2="$2"

if [ $1 = "shutdown"  ]; then
  echo "Shutting down..."
  sudo shutdown -h now

elif [ $1 = "update"  ]; then
  echo "Updating OS"
  sudo apt-get update
  sudo apt-get upgrade

fi

exit 0
